backend:
  name: github
  repo: xiaod83/conversions
  branch: main
  base_url: conversions.studio # Replace with your Vercel URL
  auth_endpoint: api.netlify.com
  

# Enable local backend for testing without authentication


media_folder: "logos"
public_folder: "/logos"

collections:
  - name: "boot-sequence"
    label: "Boot Sequence Articles"
    folder: "series/boot-sequence"
    create: true
    slug: "{{slug}}"
    extension: "html"
    format: "frontmatter"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Category", name: "category", widget: "string", default: "Boot Sequence"}
      - {label: "Excerpt", name: "excerpt", widget: "text"}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "sat"
    label: "SAT Articles"
    folder: "series/sat"
    create: true
    slug: "{{slug}}"
    extension: "html"
    format: "frontmatter"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Category", name: "category", widget: "string", default: "SAT"}
      - {label: "Excerpt", name: "excerpt", widget: "text"}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "orthopedics"
    label: "Orthopedics Articles"
    folder: "series/orthopedics"
    create: true
    slug: "{{slug}}"
    extension: "html"
    format: "frontmatter"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Category", name: "category", widget: "string", default: "Orthopedics"}
      - {label: "Excerpt", name: "excerpt", widget: "text"}
      - {label: "Body", name: "body", widget: "markdown"}
